FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    maven \
    && rm -rf /var/lib/apt/lists/*

COPY app/pom.xml .
RUN mvn dependency:go-offline

COPY app/ .
RUN mvn package

CMD ["java", "-jar", "target/app.jar"]