##
## EPITECH PROJECT, 2025
## Automakefile - Makefile (for the generator itself)
## File description:
## Build/install script-only project
##

.PHONY: all clean fclean re install tests_run

all:
	@echo "Nothing to build. Run ./automakefile to generate a Makefile in a C project."

install:
	install -m 0755 automakefile /usr/local/bin/automakefile

clean:
	@true

fclean: clean
	@true

re: all

tests_run:
	@echo "No tests for this script project."

