##
## EPITECH PROJECT, 2025
## Whanos_roro
## File description:
##   Base image for Python
##

FROM python:3.10-slim
SHELL ["/bin/bash", "-lc"]
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# No app here; used as base
CMD ["python", "-m", "app"]

