##
## EPITECH PROJECT, 2025
## Whanos_roro
## File description:
##   Standalone image for Python apps
##

FROM python:3.10-slim
SHELL ["/bin/bash", "-lc"]
WORKDIR /app

COPY requirements.txt /app/
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi

COPY . /app/

CMD ["python", "-m", "app"]

