---
- name: Install Redis
  apt:
    name: redis-server
    state: present

- name: Copy Redis configuration
  copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
    backup: yes
  notify: restart redis

- name: Enable and start Redis service
  systemd:
    name: redis-server
    enabled: yes
    state: started