##
## EPITECH PROJECT, 2024
## Antman
## File description:
## Root Makefile for both antman and giantman binaries
##

all:
	$(MAKE) -C antman
	$(MAKE) -C giantman

clean:
	$(MAKE) -C antman clean
	$(MAKE) -C giantman clean

fclean:
	$(MAKE) -C antman fclean
	$(MAKE) -C giantman fclean

re: fclean all

.PHONY: all clean fclean re