##
## EPITECH PROJECT, 2025
## Boostrap_minishell1 - Makefile
##

.PHONY: all tests_run clean fclean re

all:
	@echo "Bootstrap minishell1: nothing to build"

tests_run:
	@echo "Bootstrap minishell1: no tests"

clean:
	@true

fclean: clean
	@true

re: all

