##
## EPITECH PROJECT, 2025
## Boostrap_Amazed - Makefile
##

.PHONY: all tests_run clean fclean re

all:
	@echo "Bootstrap: nothing to build"

tests_run:
	@echo "Bootstrap: no tests"

clean:
	@true

fclean: clean
	@true

re: all

