##
## EPITECH PROJECT, 2024
## MyRadar
## File description:
## Mock Makefile for my_radar without CSFML
##

CC = gcc

CFLAGS = -Wall -Wextra -Werror -g -std=c99

NAME = my_radar

SRCDIR = src
INCDIR = include
TESTDIR = tests

SOURCES = $(SRCDIR)/mock_main.c

OBJECTS = $(SOURCES:.c=.o)

LIBS = -lm

all: $(NAME)

$(NAME): $(OBJECTS)
	$(CC) -o $(NAME) $(OBJECTS) $(LIBS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS)

fclean: clean
	rm -f $(NAME)

re: fclean all

tests_run:
	@echo "Running mock tests for my_radar..."
	@gcc -o test_my_radar $(TESTDIR)/test_main.c -DMOCK_VERSION -lm
	@./test_my_radar
	@rm -f test_my_radar

.PHONY: all clean fclean re tests_run