##
## EPITECH PROJECT, 2024
## Dante's Star
## File description:
## Main Makefile for maze generation and solving
##

all:
	$(MAKE) -C generator
	$(MAKE) -C solver

clean:
	$(MAKE) -C generator clean
	$(MAKE) -C solver clean

fclean:
	$(MAKE) -C generator fclean
	$(MAKE) -C solver fclean

re: fclean all

.PHONY: all clean fclean re