##
## EPITECH PROJECT, 2025
## Bernstein
## File description:
## Poll ingress configuration for Traefik
##

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poll-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.rule: "Host(`poll.dop.io`)"
spec:
  rules:
  - host: poll.dop.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: poll
            port:
              number: 80