##
## EPITECH PROJECT, 2025
## My_octopus
## File description:
##   No build: Ansible project helpers
##

all:
	@echo "Nothing to build for My_octopus"

clean:
	@true

fclean: clean
	@true

re: fclean all

tests_run:
	@echo "Run: ansible-playbook -i production playbook.yml"

.PHONY: all clean fclean re tests_run

