##
## EPITECH PROJECT, 2025
## NOOB - Makefile
## File description:
## Security checks scripts
##

.PHONY: all clean fclean re tests_run

all:
	@echo "NOOB: nothing to build"

tests_run:
	bash tests/test_checks.sh

clean:
	@true

fclean: clean
	@true

re: all

