##
## EPITECH PROJECT, 2025
## Chocolatine - Makefile
## File description:
## No build (workflow template project)
##

.PHONY: all clean fclean re tests_run

all:
	@echo "Chocolatine workflow template. Nothing to build."

clean:
	@true

fclean: clean
	@true

re: all

tests_run:
	@echo "No tests for workflow template."

