##
## EPITECH PROJECT, 2024
## MyHunter Mock
## File description:
## Makefile for MyHunter mock version (testing without CSFML)
##

NAME	= my_hunter

SRC	= src/mock_main.c

OBJ	= $(SRC:.c=.o)

CFLAGS	= -Wall -Wextra

all: $(NAME)

$(NAME): $(OBJ)
	gcc -o $(NAME) $(OBJ)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re